mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

####################
# Proxies
####################
proxies:
  # ===== é¦™æ¸¯ =====
  - name: "ğŸ‡­ğŸ‡° é¦™æ¸¯é«˜é€Ÿä¸“çº¿1[4K]"
    type: socks5
    server: t-uc222-10067.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-uc222-10067.ci-lab.com }

  - name: "ğŸ‡­ğŸ‡° é¦™æ¸¯é«˜é€Ÿä¸“çº¿2[4K]"
    type: socks5
    server: t-uc222-10068.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-uc222-10068.ci-lab.com }

  - name: "ğŸ‡­ğŸ‡° é¦™æ¸¯é«˜é€Ÿä¸“çº¿3[æ¨è]"
    type: socks5
    server: t-uc222-10069.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-uc222-10069.ci-lab.com }

  - name: "ğŸ‡­ğŸ‡° é¦™æ¸¯ä¸“çº¿4"
    type: socks5
    server: t-hkbn75-1001.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-hkbn75-1001.ci-lab.com }

  - name: "ğŸ‡­ğŸ‡° é¦™æ¸¯ä¸“çº¿5"
    type: socks5
    server: t-hkbn75-1002.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-hkbn75-1002.ci-lab.com }

  # ===== æ—¥æœ¬ =====
  - name: "ğŸ‡¯ğŸ‡µ æ—¥æœ¬-ä¸œäº¬1"
    type: socks5
    server: t-hkbn75-1003.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-hkbn75-1003.ci-lab.com }

  - name: "ğŸ‡¯ğŸ‡µ æ—¥æœ¬-ä¸œäº¬2"
    type: socks5
    server: t-tx104-1004.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-tx104-1004.ci-lab.com }

  # ===== äºšæ´² =====
  - name: "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡"
    type: socks5
    server: t-tx104-1005.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-tx104-1005.ci-lab.com }

  - name: "ğŸ‡¹ğŸ‡¼ å°æ¹¾-å°åŒ—"
    type: socks5
    server: t-tx104-1008.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-tx104-1008.ci-lab.com }

  - name: "ğŸ‡°ğŸ‡· éŸ©å›½-é¦–å°”"
    type: socks5
    server: t-tx104-1009.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-tx104-1009.ci-lab.com }

  # ===== æ¬§ç¾ =====
  - name: "ğŸ‡ºğŸ‡¸ ç¾å›½-æ´›æ‰çŸ¶"
    type: socks5
    server: t-tx145-1024.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-tx145-1024.ci-lab.com }

  - name: "ğŸ‡¬ğŸ‡§ è‹±å›½-ä¼¦æ•¦"
    type: socks5
    server: t-tx145-1037.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-tx145-1037.ci-lab.com }

  - name: "ğŸ‡©ğŸ‡ª å¾·å›½-æŸæ—"
    type: socks5
    server: t-tx145-1034.ci-lab.com
    port: 80
    username: "pro:u2025887"
    password: "3de79113-832d-436c-a2c6-dcf62f0be38e"
    udp: true
    network: ws
    ws-opts:
      path: /gost
      headers: { Host: t-tx145-1034.ci-lab.com }

####################
# Proxy Groups
####################
proxy-groups:
  - name: "ğŸš€ æ€»å…¥å£"
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨ä¼˜é€‰
      - ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨
      - ğŸŒ äºšæ´²è‡ªåŠ¨
      - ğŸŒ æ¬§ç¾è‡ªåŠ¨
      - DIRECT

  - name: "â™»ï¸ è‡ªåŠ¨ä¼˜é€‰"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨
      - ğŸŒ äºšæ´²è‡ªåŠ¨
      - ğŸŒ æ¬§ç¾è‡ªåŠ¨

  - name: "ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯é«˜é€Ÿä¸“çº¿1[4K]
      - ğŸ‡­ğŸ‡° é¦™æ¸¯é«˜é€Ÿä¸“çº¿2[4K]
      - ğŸ‡­ğŸ‡° é¦™æ¸¯é«˜é€Ÿä¸“çº¿3[æ¨è]
      - ğŸ‡­ğŸ‡° é¦™æ¸¯ä¸“çº¿4
      - ğŸ‡­ğŸ‡° é¦™æ¸¯ä¸“çº¿5

  - name: "ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬-ä¸œäº¬1
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬-ä¸œäº¬2

  - name: "ğŸŒ äºšæ´²è‡ªåŠ¨"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾-å°åŒ—
      - ğŸ‡°ğŸ‡· éŸ©å›½-é¦–å°”

  - name: "ğŸŒ æ¬§ç¾è‡ªåŠ¨"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ğŸ‡ºğŸ‡¸ ç¾å›½-æ´›æ‰çŸ¶
      - ğŸ‡¬ğŸ‡§ è‹±å›½-ä¼¦æ•¦
      - ğŸ‡©ğŸ‡ª å¾·å›½-æŸæ—

####################
# Rules
####################
rules:
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,ğŸš€ æ€»å…¥å£
